### ISSUE TITLE
Please add a license and screen shot

### ISSUE THREAD

**Issue by unixorn** [sohnryang/lambda-minimal-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

**Comment by sohnryang** [comment]
Thanks for your feedback!

**Comment by sohnryang** [comment]
Since I added screenshot of a demo session and license, the issue can be closed.

**Comment by unixorn** [comment]
Thanks!
